<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-GTANLOK" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.074" errors="0" timestamp="20 Jan. 2020 00:23:38 GMT">
  <testcase classname="retryLogicTests.MyTests1" name="Test1" time="0.016">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicTests.MyTests1.Test1(MyTests1.java:11)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test2" time="0.0">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogicTests.MyTests1.Test2(MyTests1.java:16)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="retryLogicTests.MyTests1" name="Test3" time="0.0"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
